project:
  type: website
  output-dir: docs

website:
  title: "Natalie Mayer"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: portfolio.qmd
        text: Portfolio
      - href: files/resume.pdf
        text: Resume

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    page-layout: full

editor: visual

