project:
  type: website
  output-dir: docs

website:
  title: "Natalie Mayer"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - California Groundwater.qmd
      - Cahokia-Joaquim Watershed.qmd
      - Willamette Falls.qmd
      - California Oil Spills.qmd
      - Pictures in Nature.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    page-layout: full

editor: visual

