project:
  type: website
  output-dir: docs

website:
  title: "Natalie Mayer"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: https://natcatmayer.shinyapps.io/groundwatershinyapp/
        text: CA Groundwater Shiny App
        target: _blank
      - href: files/cj_watershed.pdf # providing a relative file path to a pdf will open up a browser-based pdf viewer when clicked
        text: Cahokia-Joaquim Watershed
        target: _blank 
      - willamette_falls.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    page-layout: full

editor: visual

